# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: organizer/note/v1/note_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'organizer/note/v1/note_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$organizer/note/v1/note_service.proto\x12\x11organizer.note.v1\"$\n\x11\x43reateNoteRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"%\n\x12\x43reateNoteResponse\x12\x0f\n\x07note_id\x18\x01 \x01(\t\"!\n\x0eGetNoteRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\t\"\"\n\x0fGetNoteResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2\xbe\x01\n\x0bNoteService\x12[\n\nCreateNote\x12$.organizer.note.v1.CreateNoteRequest\x1a%.organizer.note.v1.CreateNoteResponse\"\x00\x12R\n\x07GetNote\x12!.organizer.note.v1.GetNoteRequest\x1a\".organizer.note.v1.GetNoteResponse\"\x00\x42\'\n\x11organizer.note.v1B\x10NoteServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'organizer.note.v1.note_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021organizer.note.v1B\020NoteServiceProtoP\001'
  _globals['_CREATENOTEREQUEST']._serialized_start=59
  _globals['_CREATENOTEREQUEST']._serialized_end=95
  _globals['_CREATENOTERESPONSE']._serialized_start=97
  _globals['_CREATENOTERESPONSE']._serialized_end=134
  _globals['_GETNOTEREQUEST']._serialized_start=136
  _globals['_GETNOTEREQUEST']._serialized_end=169
  _globals['_GETNOTERESPONSE']._serialized_start=171
  _globals['_GETNOTERESPONSE']._serialized_end=205
  _globals['_NOTESERVICE']._serialized_start=208
  _globals['_NOTESERVICE']._serialized_end=398
# @@protoc_insertion_point(module_scope)
