# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from organizer.note.v1 import note_service_pb2 as organizer_dot_note_dot_v1_dot_note__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in organizer/note/v1/note_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NoteServiceStub(object):
    """A set of methods for managing notes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNote = channel.unary_unary(
                '/organizer.note.v1.NoteService/CreateNote',
                request_serializer=organizer_dot_note_dot_v1_dot_note__service__pb2.CreateNoteRequest.SerializeToString,
                response_deserializer=organizer_dot_note_dot_v1_dot_note__service__pb2.CreateNoteResponse.FromString,
                _registered_method=True)
        self.GetNote = channel.unary_unary(
                '/organizer.note.v1.NoteService/GetNote',
                request_serializer=organizer_dot_note_dot_v1_dot_note__service__pb2.GetNoteRequest.SerializeToString,
                response_deserializer=organizer_dot_note_dot_v1_dot_note__service__pb2.GetNoteResponse.FromString,
                _registered_method=True)


class NoteServiceServicer(object):
    """A set of methods for managing notes.
    """

    def CreateNote(self, request, context):
        """Creates a new note with the specified content.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNote(self, request, context):
        """Retrieves the content of an existing note by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNote,
                    request_deserializer=organizer_dot_note_dot_v1_dot_note__service__pb2.CreateNoteRequest.FromString,
                    response_serializer=organizer_dot_note_dot_v1_dot_note__service__pb2.CreateNoteResponse.SerializeToString,
            ),
            'GetNote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNote,
                    request_deserializer=organizer_dot_note_dot_v1_dot_note__service__pb2.GetNoteRequest.FromString,
                    response_serializer=organizer_dot_note_dot_v1_dot_note__service__pb2.GetNoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'organizer.note.v1.NoteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('organizer.note.v1.NoteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NoteService(object):
    """A set of methods for managing notes.
    """

    @staticmethod
    def CreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/organizer.note.v1.NoteService/CreateNote',
            organizer_dot_note_dot_v1_dot_note__service__pb2.CreateNoteRequest.SerializeToString,
            organizer_dot_note_dot_v1_dot_note__service__pb2.CreateNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/organizer.note.v1.NoteService/GetNote',
            organizer_dot_note_dot_v1_dot_note__service__pb2.GetNoteRequest.SerializeToString,
            organizer_dot_note_dot_v1_dot_note__service__pb2.GetNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
